theme = "nord-night"

[editor]
bufferline = "multiple"
cursorline = true
line-number = "relative"
rulers = [120]
true-color = true
color-modes = true
popup-border = "all"

[editor.indent-guides]
render = true
character = '⸽'
skip-levels = 1

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.whitespace.render]
newline = "all"

[editor.whitespace.characters]
newline = "↵"
tabpad = "·" # Tabs will look like "→···"

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name", "file-modification-indicator"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.insert]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"

[keys.normal]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"


